/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare namespace Duration {
  export function add(base: Duration, other: Duration): Duration
  export function div(base: Duration, other: number): Duration
  export function fromMicros(micros: number): Duration
  export function fromMillis(millis: number): Duration
  export function fromNanos(nanos: number): Duration
  export function fromSecs(secs: number): Duration
  export function mul(base: Duration, other: number): Duration
  export function sub(base: Duration, other: Duration): Duration
}

export declare namespace Extra {
  export class BufferSurface {
    constructor(window: Window)
    presentWithTyped(input: Uint32Array): void
    presentWithWriter(write: (view: Uint32Array, width: number, height: number) => void): void
    presentWithThreadsafeWriter(write: (view: Uint32Array, width: number, height: number) => void): void
  }
  export class ThreadPool {
    constructor(numThreads: number)
    static default(): ThreadPool
    static main(): ThreadPool
    execute(callback: () => (Promise<void> | void)): void
  }
  export interface SurfaceOptions {
    system: Extra.SurfaceSystem
    windowHandle: bigint
    displayHandle: bigint
  }
  export const enum SurfaceSystem {
    Win32 = 'win32',
    Cocoa = 'cocoa',
    X11 = 'x11',
    Wayland = 'wayland'
  }
  export function threadInterval(duration: Duration, exec: () => (Promise<void> | void)): void
  export function tokioCallSpawn(callback: () => (Promise<void> | void)): void
  export function tokioInterval(duration: Duration, exec: () => (Promise<void> | void)): void
  export function tokioSleep(duration: Duration): Promise<void>
}

export declare namespace Instant {
  export function add(base: Instant, other: Duration): Instant
  export function afterMicros(micros: number): Instant
  export function afterMillis(millis: number): Instant
  export function afterNanos(nanos: number): Instant
  export function afterSecs(secs: number): Instant
  export function durationSince(base: Instant, other: Instant): Duration
  export function now(): Instant
  export function sub(base: Instant, other: Duration): Instant
}

/** [winit::window::ActivationToken] */
export declare class ActivationToken {

}

export declare class ActiveEventLoop {
  createWindow(windowAttributes: WindowAttributes): Window
  availableMonitors(): Array<MonitorHandle>
  primaryMonitor(): MonitorHandle | null
  listenDeviceEvents(allowed: DeviceEvents): void
  systemTheme(): Theme | null
  setControlFlow(controlFlow: ControlFlow): void
  controlFlow(): ControlFlow
  exit(): void
  exiting(): boolean
  ownedDisplayHandle(): OwnedDisplayHandle
}

export declare class Application {
  static withOptions(options: ApplicationCallbacks): Application
}

/** [winit::event_loop::AsyncRequestSerial]  */
export declare class AsyncRequestSerial {

}

export declare class Cursor {
  static fromIcon(icon: CursorIcon): Cursor
  static fromCustom(custom: CustomCursor): Cursor
}

export declare class CustomCursor {
  static fromRgba(rgba: Uint8Array, width: number, height: number, hotspotX: number, hotspotY: number): CustomCursorSource
}

export declare class CustomCursorSource {

}

/** [winit::data_transfer::DataTransferId] */
export declare class DataTransferId {

}

/** [winit::event::DeviceId] */
export declare class DeviceId {

}

export declare class EventLoop {
  constructor()
  runApp(app: Application): void
  runAppOnDemand(app: Application): void
  pumpAppEvents(timeout: Duration | undefined | null, app: Application): PumpStatus
}

/** [winit::event::FingerId] */
export declare class FingerId {

}

export declare class Icon {
  static fromRgba(rgba: Uint8Array, width: number, height: number): Icon
}

/** [winit::event::KeyEvent]  */
export declare class KeyEvent {
  get physicalKey(): PhysicalKey
  get logicalKey(): Key
  get text(): string | null
  get location(): KeyLocation
  get state(): ElementState
  get repeat(): boolean
}

/** [winit::event::Modifiers]  */
export declare class Modifiers {
  get state(): ModifiersState
}

export declare class ModifiersState {
  static all(): ModifiersState
  static empty(): ModifiersState
  isAll(): boolean
  isEmpty(): boolean
  hasShift(): boolean
  hasControl(): boolean
  hasAlt(): boolean
  hasMeta(): boolean
  toggleShift(): this
  toggleControl(): this
  toggleAlt(): this
  toggleMeta(): this
  insertShift(): this
  insertControl(): this
  insertAlt(): this
  insertMeta(): this
  removeShift(): this
  removeControl(): this
  removeAlt(): this
  removeMeta(): this
}

/** [winit::monitor::MonitorHandle] */
export declare class MonitorHandle {
  /**
   * Returns a human-readable name of the monitor.
   *
   * Returns `None` if the monitor doesn't exist anymore.
   */
  name(): string | null
  /**
   * The monitor refresh rate used by the system.
   *
   * Return `Some` if succeed, or `None` if failed, which usually happens when the monitor
   * the window is on is removed.
   *
   * When using exclusive fullscreen, the refresh rate of the [`winit::monitor::VideoMode`] that was
   * used to enter fullscreen should be used instead.
   */
  position(): Position | null
  /**
   * Returns the scale factor of the underlying monitor. To map logical pixels to physical
   * pixels and vice versa, use [`Window::scale_factor`].
   *
   * See the [`dpi`] module for more information.
   *
   * ## Platform-specific
   *
   * - **X11:** Can be overridden using the `WINIT_X11_SCALE_FACTOR` environment variable.
   * - **Wayland:** May differ from [`Window::scale_factor`].
   * - **Android:** Always returns 1.0.
   *
   * [`Window::scale_factor`]: crate::window::Window::scale_factor
   */
  scaleFactor(): number
  /**
   * Returns all fullscreen video modes supported by this monitor.
   *
   * ## Platform-specific
   *
   * - **Web:** Always returns an empty iterator
   */
  videoModes(): Array<VideoMode>
  /** Returns an identifier that persistently changes across a system reboot. */
  id(): bigint
  /** Returns a platform-native identifier for the monitor. */
  nativeId(): bigint
  /**
   * Returns the current video mode of this monitor.
   *
   * This is useful to acquire the monitor's size and refresh rate.
   */
  currentVideoMode(): VideoMode | null
}

/** [winit::event_loop::OwnedDisplayHandle]  */
export declare class OwnedDisplayHandle {

}

/** [winit::event::RawKeyEvent] */
export declare class RawKeyEvent {
  get physicalKey(): PhysicalKey
  get state(): ElementState
}

/** [winit::event::SurfaceSizeWriter] */
export declare class SurfaceSizeWriter {

}

/** [winit::monitor::VideoMode] */
export declare class VideoMode {
  /** Returns the resolution of this video mode. */
  size(): Size
  /**
   * Returns the bit depth of this video mode, as in how many bits you have
   * available per color. This is generally 24 bits or 32 bits on modern
   * systems, depending on whether the alpha channel is counted or not.
   *
   * ## Platform-specific
   *
   * - **Wayland / Orbital:** Always returns 32.
   * - **iOS:** Always returns 32.
   */
  bitDepth(): number | null
  /** Returns the refresh rate of this video mode in mHz. */
  refreshRateMillihertz(): number | null
}

export declare class Window {
  static defaultAttributes(): WindowAttributes
  requestImeUpdate(request: ImeRequest): void
  id(): WindowId
  scaleFactor(): number
  requestRedraw(): void
  prePresentNotify(): void
  resetDeadKeys(): void
  surfacePosition(): Position
  outerPosition(): Position
  setOuterPosition(position: Position): void
  surfaceSize(): Size
  requestSurfaceSize(size: Size): Size | null
  outerSize(): Size
  setMinSurfaceSize(minSize?: Size | undefined | null): void
  setMaxSurfaceSize(maxSize?: Size | undefined | null): void
  surfaceResizeIncrements(): Size | null
  setSurfaceResizeIncrements(increments?: Size | undefined | null): void
  setTitle(title: string): void
  setTransparent(transparent: boolean): void
  setBlur(blur: boolean): void
  setVisible(visible: boolean): void
  isVisible(): boolean | null
  setResizable(resizable: boolean): void
  isResizable(): boolean
  setEnabledButtons(buttons: WindowButtons): void
  enabledButtons(): WindowButtons
  setMinimized(minimized: boolean): void
  isMinimized(): boolean | null
  setMaximized(maximized: boolean): void
  isMaximized(): boolean
  setDecorations(decorations: boolean): void
  isDecorated(): boolean
  setWindowLevel(level: WindowLevel): void
  setWindowIcon(windowIcon?: Icon | undefined | null): void
  focusWindow(): void
  hasFocus(): boolean
  requestUserAttention(requestType?: UserAttentionType | undefined | null): void
  setTheme(theme?: Theme | undefined | null): void
  theme(): Theme | null
  setContentProtected(protected: boolean): void
  title(): string
  setFullscreen(fullscreen?: Fullscreen | undefined | null): void
  fullscreen(): Fullscreen | null
  setCursor(cursor: Cursor): void
  setCursorPosition(position: Position): void
  setCursorGrab(mode: CursorGrabMode): void
  setCursorVisible(visible: boolean): void
  dragWindow(): void
  dragResizeWindow(direction: ResizeDirection): void
  showWindowMenu(position: Position): void
  setCursorHittest(hittest: boolean): void
  currentMonitor(): MonitorHandle | null
  availableMonitors(): Array<MonitorHandle>
  primaryMonitor(): MonitorHandle | null
}

export declare class WindowAttributes {
  constructor()
  withSurfaceSize(size: Size): this
  withMinSurfaceSize(minSize: Size): this
  withMaxSurfaceSize(maxSize: Size): this
  withPosition(position: Position): this
  withResizable(resizable: boolean): this
  withEnabledButtons(buttons: WindowButtons): this
  withTitle(title: string): this
  withFullscreen(fullscreen?: Fullscreen | undefined | null): this
  withMaximized(maximized: boolean): this
  withVisible(visible: boolean): this
  withTransparent(transparent: boolean): this
  get transparent(): boolean
  withBlur(blur: boolean): this
  withDecorations(decorations: boolean): this
  withWindowLevel(level: WindowLevel): this
  withTheme(theme?: Theme | undefined | null): this
  withSurfaceResizeIncrements(resizeIncrements: Size): this
  withContentProtected(protected: boolean): this
  withActive(active: boolean): this
  withCursor(cursor: Cursor): this
}

/** [winit::window::WindowButtons] */
export declare class WindowButtons {
  static all(): WindowButtons
  static empty(): WindowButtons
  isAll(): boolean
  isEmpty(): boolean
  hasClose(): boolean
  hasMinimize(): boolean
  hasMaximize(): boolean
  toggleClose(): this
  toggleMinimize(): this
  toggleMaximize(): this
  insertClose(): this
  insertMinimize(): this
  insertMaximize(): this
  removeClose(): this
  removeMinimize(): this
  removeMaximize(): this
}

/** [winit::window::WindowId] */
export declare class WindowId {
  raw(): bigint
  rawString(): string
}

export interface ApplicationCallbacks {
  onNewEvents?: (eventLoop: ActiveEventLoop, cause: StartCause) => unknown
  onResumed?: (eventLoop: ActiveEventLoop) => unknown
  onCanCreateSurfaces: (eventLoop: ActiveEventLoop) => unknown
  onProxyWakeUp?: (eventLoop: ActiveEventLoop) => unknown
  onWindowEvent: (eventLoop: ActiveEventLoop, windowId: WindowId, event: WindowEvent) => unknown
  onDeviceEvent?: (eventLoop: ActiveEventLoop, deviceId: DeviceId | null, event: DeviceEvent) => unknown
  onAboutToWait?: (eventLoop: ActiveEventLoop) => unknown
  onSuspended?: (eventLoop: ActiveEventLoop) => unknown
  onDestroySurfaces?: (eventLoop: ActiveEventLoop) => unknown
  onMemoryWarning?: (eventLoop: ActiveEventLoop) => unknown
}

/** [winit::event::ButtonSource] */
export type ButtonSource =
  | { type: 'Mouse', button: MouseButton }
  | { type: 'Touch', fingerId: FingerId, force?: Force }
  | { type: 'TabletTool', kind: TabletToolKind, button: TabletToolButton, data: TabletToolData }
  | { type: 'Unknown', code: number }
  | { type: 'NonExhaustive' }

export type ControlFlow =
  | { type: 'Poll' }
  | { type: 'Wait' }
  | { type: 'WaitUntil', timeout: Instant }

export declare const enum CursorGrabMode {
  None = 'None',
  Confined = 'Confined',
  Locked = 'Locked'
}

/** [`winit::cursor::CursorIcon`]  */
export declare const enum CursorIcon {
  Default = 'Default',
  ContextMenu = 'ContextMenu',
  Help = 'Help',
  Pointer = 'Pointer',
  Progress = 'Progress',
  Wait = 'Wait',
  Cell = 'Cell',
  Crosshair = 'Crosshair',
  Text = 'Text',
  VerticalText = 'VerticalText',
  Alias = 'Alias',
  Copy = 'Copy',
  Move = 'Move',
  NoDrop = 'NoDrop',
  NotAllowed = 'NotAllowed',
  Grab = 'Grab',
  Grabbing = 'Grabbing',
  EResize = 'EResize',
  NResize = 'NResize',
  NeResize = 'NeResize',
  NwResize = 'NwResize',
  SResize = 'SResize',
  SeResize = 'SeResize',
  SwResize = 'SwResize',
  WResize = 'WResize',
  EwResize = 'EwResize',
  NsResize = 'NsResize',
  NeswResize = 'NeswResize',
  NwseResize = 'NwseResize',
  ColResize = 'ColResize',
  RowResize = 'RowResize',
  AllScroll = 'AllScroll',
  ZoomIn = 'ZoomIn',
  ZoomOut = 'ZoomOut',
  NonExhaustive = 'NonExhaustive'
}

/** [winit::event::DeviceEvent] */
export type DeviceEvent =
  | { type: 'PointerMotion', delta: Position }
  | { type: 'MouseWheel', delta: MouseScrollDelta }
  | { type: 'Button', button: number, state: ElementState }
  | { type: 'Key', raw: RawKeyEvent }
  | { type: 'NonExhaustive' }

export declare const enum DeviceEvents {
  Always = 'Always',
  WhenFocused = 'WhenFocused',
  Never = 'Never'
}

/** [winit::event_loop::DndAction] */
export declare const enum DndAction {
  Move = 'Move',
  Copy = 'Copy',
  Link = 'Link',
  Ask = 'Ask',
  Private = 'Private',
  NonExhaustive = 'NonExhaustive'
}

export interface Duration {
  secs: number
  nanos: number
}

export declare const enum ElementState {
  Pressed = 'Pressed',
  Released = 'Released'
}

export type Force =
  | { type: 'Calibrated', /**
   * The force of the touch, where a value of 1.0 represents the force of
   * an average touch (predetermined by the system, not user-specific).
   *
   * The force reported by Apple Pencil is measured along the axis of the
   * pencil. If you want a force perpendicular to the device, you need to
   * calculate this value using the `altitude_angle` value.
   */
  force: number, /**
   * The maximum possible force for a touch.
   *
   * The value of this field is sufficiently high to provide a wide
   * dynamic range for values of the `force` field.
   */
maxPossibleForce: number }
| { type: 'Normalized', value: number }

export type Fullscreen =
  | { type: 'Exclusive', monitor: MonitorHandle, videoMode: VideoMode }
  | { type: 'Borderless', monitor?: MonitorHandle }

/** [winit::event::Ime] */
export type Ime =
  | { type: 'Enabled' }
  | { type: 'Preedit', preedit: string, cursor?: PreeditCursorPosition }
  | { type: 'Commit', commit: string }
  | { type: 'Disabled' }
  | { type: 'NonExhaustive' }

/** [winit::window::ImeCapabilities] */
export interface ImeCapabilities {
  hintAndPurpose: boolean
  cursorArea: boolean
  surroundingText: boolean
}

export interface ImeCursorArea {
  position: Position
  size: Size
}

/** [winit::window::ImeHint] */
export interface ImeHint {
  completion: boolean
  spellcheck: boolean
  autoCapitalization: boolean
  lowercase: boolean
  uppercase: boolean
  titlecase: boolean
  hiddenText: boolean
  sensitiveData: boolean
  latin: boolean
  multiline: boolean
}

export interface ImeHintAndPurpose {
  hint: ImeHint
  purpose: ImePurpose
}

/** [winit::window::ImePurpose] */
export declare const enum ImePurpose {
  Normal = 'Normal',
  Password = 'Password',
  Terminal = 'Terminal',
  Number = 'Number',
  Phone = 'Phone',
  Url = 'Url',
  Email = 'Email',
  Pin = 'Pin',
  Date = 'Date',
  Time = 'Time',
  DateTime = 'DateTime',
  NonExhaustive = 'NonExhaustive'
}

/** [winit::window::ImeRequest] */
export type ImeRequest =
  | { type: 'Enable', capabilities: ImeCapabilities, data: ImeRequestData }
  | { type: 'Update', data: ImeRequestData }
  | { type: 'Disable' }

/** [winit::window::ImeRequestData] */
export interface ImeRequestData {
  hintAndPurpose?: ImeHintAndPurpose
  cursorArea?: ImeCursorArea
  surroundingText?: ImeSurroundingText
}

/** [winit::window::ImeSurroundingText] */
export interface ImeSurroundingText {
  text: string
  cursor: number
  anchor: number
}

export interface Instant {
  secs: number
  nanos: number
}

export type Key =
  | { type: 'Named', name: NamedKey }
  | { type: 'Character', ch: string }
  | { type: 'Unidentified', ch: NativeKey }
  | { type: 'Dead', ch?: string }

export declare const enum KeyCode {
  Backquote = 'Backquote',
  Backslash = 'Backslash',
  BracketLeft = 'BracketLeft',
  BracketRight = 'BracketRight',
  Comma = 'Comma',
  Digit0 = 'Digit0',
  Digit1 = 'Digit1',
  Digit2 = 'Digit2',
  Digit3 = 'Digit3',
  Digit4 = 'Digit4',
  Digit5 = 'Digit5',
  Digit6 = 'Digit6',
  Digit7 = 'Digit7',
  Digit8 = 'Digit8',
  Digit9 = 'Digit9',
  Equal = 'Equal',
  IntlBackslash = 'IntlBackslash',
  IntlRo = 'IntlRo',
  IntlYen = 'IntlYen',
  KeyA = 'KeyA',
  KeyB = 'KeyB',
  KeyC = 'KeyC',
  KeyD = 'KeyD',
  KeyE = 'KeyE',
  KeyF = 'KeyF',
  KeyG = 'KeyG',
  KeyH = 'KeyH',
  KeyI = 'KeyI',
  KeyJ = 'KeyJ',
  KeyK = 'KeyK',
  KeyL = 'KeyL',
  KeyM = 'KeyM',
  KeyN = 'KeyN',
  KeyO = 'KeyO',
  KeyP = 'KeyP',
  KeyQ = 'KeyQ',
  KeyR = 'KeyR',
  KeyS = 'KeyS',
  KeyT = 'KeyT',
  KeyU = 'KeyU',
  KeyV = 'KeyV',
  KeyW = 'KeyW',
  KeyX = 'KeyX',
  KeyY = 'KeyY',
  KeyZ = 'KeyZ',
  Minus = 'Minus',
  Period = 'Period',
  Quote = 'Quote',
  Semicolon = 'Semicolon',
  Slash = 'Slash',
  AltLeft = 'AltLeft',
  AltRight = 'AltRight',
  Backspace = 'Backspace',
  CapsLock = 'CapsLock',
  ContextMenu = 'ContextMenu',
  ControlLeft = 'ControlLeft',
  ControlRight = 'ControlRight',
  Enter = 'Enter',
  MetaLeft = 'MetaLeft',
  MetaRight = 'MetaRight',
  ShiftLeft = 'ShiftLeft',
  ShiftRight = 'ShiftRight',
  Space = 'Space',
  Tab = 'Tab',
  Convert = 'Convert',
  KanaMode = 'KanaMode',
  Lang1 = 'Lang1',
  Lang2 = 'Lang2',
  Lang3 = 'Lang3',
  Lang4 = 'Lang4',
  Lang5 = 'Lang5',
  NonConvert = 'NonConvert',
  Delete = 'Delete',
  End = 'End',
  Help = 'Help',
  Home = 'Home',
  Insert = 'Insert',
  PageDown = 'PageDown',
  PageUp = 'PageUp',
  ArrowDown = 'ArrowDown',
  ArrowLeft = 'ArrowLeft',
  ArrowRight = 'ArrowRight',
  ArrowUp = 'ArrowUp',
  NumLock = 'NumLock',
  Numpad0 = 'Numpad0',
  Numpad1 = 'Numpad1',
  Numpad2 = 'Numpad2',
  Numpad3 = 'Numpad3',
  Numpad4 = 'Numpad4',
  Numpad5 = 'Numpad5',
  Numpad6 = 'Numpad6',
  Numpad7 = 'Numpad7',
  Numpad8 = 'Numpad8',
  Numpad9 = 'Numpad9',
  NumpadAdd = 'NumpadAdd',
  NumpadBackspace = 'NumpadBackspace',
  NumpadClear = 'NumpadClear',
  NumpadClearEntry = 'NumpadClearEntry',
  NumpadComma = 'NumpadComma',
  NumpadDecimal = 'NumpadDecimal',
  NumpadDivide = 'NumpadDivide',
  NumpadEnter = 'NumpadEnter',
  NumpadEqual = 'NumpadEqual',
  NumpadHash = 'NumpadHash',
  NumpadMemoryAdd = 'NumpadMemoryAdd',
  NumpadMemoryClear = 'NumpadMemoryClear',
  NumpadMemoryRecall = 'NumpadMemoryRecall',
  NumpadMemoryStore = 'NumpadMemoryStore',
  NumpadMemorySubtract = 'NumpadMemorySubtract',
  NumpadMultiply = 'NumpadMultiply',
  NumpadParenLeft = 'NumpadParenLeft',
  NumpadParenRight = 'NumpadParenRight',
  NumpadStar = 'NumpadStar',
  NumpadSubtract = 'NumpadSubtract',
  Escape = 'Escape',
  Fn = 'Fn',
  FnLock = 'FnLock',
  PrintScreen = 'PrintScreen',
  ScrollLock = 'ScrollLock',
  Pause = 'Pause',
  BrowserBack = 'BrowserBack',
  BrowserFavorites = 'BrowserFavorites',
  BrowserForward = 'BrowserForward',
  BrowserHome = 'BrowserHome',
  BrowserRefresh = 'BrowserRefresh',
  BrowserSearch = 'BrowserSearch',
  BrowserStop = 'BrowserStop',
  Eject = 'Eject',
  LaunchApp1 = 'LaunchApp1',
  LaunchApp2 = 'LaunchApp2',
  LaunchMail = 'LaunchMail',
  MediaPlayPause = 'MediaPlayPause',
  MediaSelect = 'MediaSelect',
  MediaStop = 'MediaStop',
  MediaTrackNext = 'MediaTrackNext',
  MediaTrackPrevious = 'MediaTrackPrevious',
  Power = 'Power',
  Sleep = 'Sleep',
  AudioVolumeDown = 'AudioVolumeDown',
  AudioVolumeMute = 'AudioVolumeMute',
  AudioVolumeUp = 'AudioVolumeUp',
  WakeUp = 'WakeUp',
  Abort = 'Abort',
  Resume = 'Resume',
  Suspend = 'Suspend',
  Again = 'Again',
  Copy = 'Copy',
  Cut = 'Cut',
  Find = 'Find',
  Open = 'Open',
  Paste = 'Paste',
  Props = 'Props',
  Select = 'Select',
  Undo = 'Undo',
  Hiragana = 'Hiragana',
  Katakana = 'Katakana',
  F1 = 'F1',
  F2 = 'F2',
  F3 = 'F3',
  F4 = 'F4',
  F5 = 'F5',
  F6 = 'F6',
  F7 = 'F7',
  F8 = 'F8',
  F9 = 'F9',
  F10 = 'F10',
  F11 = 'F11',
  F12 = 'F12',
  F13 = 'F13',
  F14 = 'F14',
  F15 = 'F15',
  F16 = 'F16',
  F17 = 'F17',
  F18 = 'F18',
  F19 = 'F19',
  F20 = 'F20',
  F21 = 'F21',
  F22 = 'F22',
  F23 = 'F23',
  F24 = 'F24',
  F25 = 'F25',
  F26 = 'F26',
  F27 = 'F27',
  F28 = 'F28',
  F29 = 'F29',
  F30 = 'F30',
  F31 = 'F31',
  F32 = 'F32',
  F33 = 'F33',
  F34 = 'F34',
  F35 = 'F35',
  NonExhaustive = 'NonExhaustive'
}

export declare const enum KeyLocation {
  Standard = 'Standard',
  Left = 'Left',
  Right = 'Right',
  Numpad = 'Numpad'
}

export declare const enum ModifiersKeyState {
  Pressed = 'Pressed',
  Unknown = 'Unknown'
}

/** [winit::event::MouseButton] */
export type MouseButton =
  | { type: 'Left', discriminant: 0 }
  | { type: 'Right', discriminant: 1 }
  | { type: 'Middle', discriminant: 2 }
  | { type: 'Back', discriminant: 3 }
  | { type: 'Forward', discriminant: 4 }
  | { type: 'Button6', discriminant: 5 }
  | { type: 'Button7', discriminant: 6 }
  | { type: 'Button8', discriminant: 7 }
  | { type: 'Button9', discriminant: 8 }
  | { type: 'Button10', discriminant: 9 }
  | { type: 'Button11', discriminant: 10 }
  | { type: 'Button12', discriminant: 11 }
  | { type: 'Button13', discriminant: 12 }
  | { type: 'Button14', discriminant: 13 }
  | { type: 'Button15', discriminant: 14 }
  | { type: 'Button16', discriminant: 15 }
  | { type: 'Button17', discriminant: 16 }
  | { type: 'Button18', discriminant: 17 }
  | { type: 'Button19', discriminant: 18 }
  | { type: 'Button20', discriminant: 19 }
  | { type: 'Button21', discriminant: 20 }
  | { type: 'Button22', discriminant: 21 }
  | { type: 'Button23', discriminant: 22 }
  | { type: 'Button24', discriminant: 23 }
  | { type: 'Button25', discriminant: 24 }
  | { type: 'Button26', discriminant: 25 }
  | { type: 'Button27', discriminant: 26 }
  | { type: 'Button28', discriminant: 27 }
  | { type: 'Button29', discriminant: 28 }
  | { type: 'Button30', discriminant: 29 }
  | { type: 'Button31', discriminant: 30 }
  | { type: 'Button32', discriminant: 31 }

export type MouseScrollDelta =
  | { type: 'LineDelta', x: number, y: number }
  | { type: 'PixelDelta', delta: Position }
  | { type: 'NonExhaustive' }

export declare const enum NamedKey {
  Alt = 'Alt',
  AltGraph = 'AltGraph',
  CapsLock = 'CapsLock',
  Control = 'Control',
  Fn = 'Fn',
  FnLock = 'FnLock',
  NumLock = 'NumLock',
  ScrollLock = 'ScrollLock',
  Shift = 'Shift',
  Symbol = 'Symbol',
  SymbolLock = 'SymbolLock',
  Meta = 'Meta',
  Enter = 'Enter',
  Tab = 'Tab',
  ArrowDown = 'ArrowDown',
  ArrowLeft = 'ArrowLeft',
  ArrowRight = 'ArrowRight',
  ArrowUp = 'ArrowUp',
  End = 'End',
  Home = 'Home',
  PageDown = 'PageDown',
  PageUp = 'PageUp',
  Backspace = 'Backspace',
  Clear = 'Clear',
  Copy = 'Copy',
  CrSel = 'CrSel',
  Cut = 'Cut',
  Delete = 'Delete',
  EraseEof = 'EraseEof',
  ExSel = 'ExSel',
  Insert = 'Insert',
  Paste = 'Paste',
  Redo = 'Redo',
  Undo = 'Undo',
  Accept = 'Accept',
  Again = 'Again',
  Attn = 'Attn',
  Cancel = 'Cancel',
  ContextMenu = 'ContextMenu',
  Escape = 'Escape',
  Execute = 'Execute',
  Find = 'Find',
  Help = 'Help',
  Pause = 'Pause',
  Play = 'Play',
  Props = 'Props',
  Select = 'Select',
  ZoomIn = 'ZoomIn',
  ZoomOut = 'ZoomOut',
  BrightnessDown = 'BrightnessDown',
  BrightnessUp = 'BrightnessUp',
  Eject = 'Eject',
  LogOff = 'LogOff',
  Power = 'Power',
  PowerOff = 'PowerOff',
  PrintScreen = 'PrintScreen',
  Hibernate = 'Hibernate',
  Standby = 'Standby',
  WakeUp = 'WakeUp',
  AllCandidates = 'AllCandidates',
  Alphanumeric = 'Alphanumeric',
  CodeInput = 'CodeInput',
  Compose = 'Compose',
  Convert = 'Convert',
  FinalMode = 'FinalMode',
  GroupFirst = 'GroupFirst',
  GroupLast = 'GroupLast',
  GroupNext = 'GroupNext',
  GroupPrevious = 'GroupPrevious',
  ModeChange = 'ModeChange',
  NextCandidate = 'NextCandidate',
  NonConvert = 'NonConvert',
  PreviousCandidate = 'PreviousCandidate',
  Process = 'Process',
  SingleCandidate = 'SingleCandidate',
  HangulMode = 'HangulMode',
  HanjaMode = 'HanjaMode',
  JunjaMode = 'JunjaMode',
  Eisu = 'Eisu',
  Hankaku = 'Hankaku',
  Hiragana = 'Hiragana',
  HiraganaKatakana = 'HiraganaKatakana',
  KanaMode = 'KanaMode',
  KanjiMode = 'KanjiMode',
  Katakana = 'Katakana',
  Romaji = 'Romaji',
  Zenkaku = 'Zenkaku',
  ZenkakuHankaku = 'ZenkakuHankaku',
  Soft1 = 'Soft1',
  Soft2 = 'Soft2',
  Soft3 = 'Soft3',
  Soft4 = 'Soft4',
  ChannelDown = 'ChannelDown',
  ChannelUp = 'ChannelUp',
  Close = 'Close',
  MailForward = 'MailForward',
  MailReply = 'MailReply',
  MailSend = 'MailSend',
  MediaClose = 'MediaClose',
  MediaFastForward = 'MediaFastForward',
  MediaPause = 'MediaPause',
  MediaPlay = 'MediaPlay',
  MediaPlayPause = 'MediaPlayPause',
  MediaRecord = 'MediaRecord',
  MediaRewind = 'MediaRewind',
  MediaStop = 'MediaStop',
  MediaTrackNext = 'MediaTrackNext',
  MediaTrackPrevious = 'MediaTrackPrevious',
  New = 'New',
  Open = 'Open',
  Print = 'Print',
  Save = 'Save',
  SpellCheck = 'SpellCheck',
  Key11 = 'Key11',
  Key12 = 'Key12',
  AudioBalanceLeft = 'AudioBalanceLeft',
  AudioBalanceRight = 'AudioBalanceRight',
  AudioBassBoostDown = 'AudioBassBoostDown',
  AudioBassBoostToggle = 'AudioBassBoostToggle',
  AudioBassBoostUp = 'AudioBassBoostUp',
  AudioFaderFront = 'AudioFaderFront',
  AudioFaderRear = 'AudioFaderRear',
  AudioSurroundModeNext = 'AudioSurroundModeNext',
  AudioTrebleDown = 'AudioTrebleDown',
  AudioTrebleUp = 'AudioTrebleUp',
  AudioVolumeDown = 'AudioVolumeDown',
  AudioVolumeUp = 'AudioVolumeUp',
  AudioVolumeMute = 'AudioVolumeMute',
  MicrophoneToggle = 'MicrophoneToggle',
  MicrophoneVolumeDown = 'MicrophoneVolumeDown',
  MicrophoneVolumeUp = 'MicrophoneVolumeUp',
  MicrophoneVolumeMute = 'MicrophoneVolumeMute',
  SpeechCorrectionList = 'SpeechCorrectionList',
  SpeechInputToggle = 'SpeechInputToggle',
  LaunchApplication1 = 'LaunchApplication1',
  LaunchApplication2 = 'LaunchApplication2',
  LaunchCalendar = 'LaunchCalendar',
  LaunchContacts = 'LaunchContacts',
  LaunchMail = 'LaunchMail',
  LaunchMediaPlayer = 'LaunchMediaPlayer',
  LaunchMusicPlayer = 'LaunchMusicPlayer',
  LaunchPhone = 'LaunchPhone',
  LaunchScreenSaver = 'LaunchScreenSaver',
  LaunchSpreadsheet = 'LaunchSpreadsheet',
  LaunchWebBrowser = 'LaunchWebBrowser',
  LaunchWebCam = 'LaunchWebCam',
  LaunchWordProcessor = 'LaunchWordProcessor',
  BrowserBack = 'BrowserBack',
  BrowserFavorites = 'BrowserFavorites',
  BrowserForward = 'BrowserForward',
  BrowserHome = 'BrowserHome',
  BrowserRefresh = 'BrowserRefresh',
  BrowserSearch = 'BrowserSearch',
  BrowserStop = 'BrowserStop',
  AppSwitch = 'AppSwitch',
  Call = 'Call',
  Camera = 'Camera',
  CameraFocus = 'CameraFocus',
  EndCall = 'EndCall',
  GoBack = 'GoBack',
  GoHome = 'GoHome',
  HeadsetHook = 'HeadsetHook',
  LastNumberRedial = 'LastNumberRedial',
  Notification = 'Notification',
  MannerMode = 'MannerMode',
  VoiceDial = 'VoiceDial',
  TV = 'TV',
  TV3DMode = 'TV3DMode',
  TVAntennaCable = 'TVAntennaCable',
  TVAudioDescription = 'TVAudioDescription',
  TVAudioDescriptionMixDown = 'TVAudioDescriptionMixDown',
  TVAudioDescriptionMixUp = 'TVAudioDescriptionMixUp',
  TVContentsMenu = 'TVContentsMenu',
  TVDataService = 'TVDataService',
  TVInput = 'TVInput',
  TVInputComponent1 = 'TVInputComponent1',
  TVInputComponent2 = 'TVInputComponent2',
  TVInputComposite1 = 'TVInputComposite1',
  TVInputComposite2 = 'TVInputComposite2',
  TVInputHDMI1 = 'TVInputHDMI1',
  TVInputHDMI2 = 'TVInputHDMI2',
  TVInputHDMI3 = 'TVInputHDMI3',
  TVInputHDMI4 = 'TVInputHDMI4',
  TVInputVGA1 = 'TVInputVGA1',
  TVMediaContext = 'TVMediaContext',
  TVNetwork = 'TVNetwork',
  TVNumberEntry = 'TVNumberEntry',
  TVPower = 'TVPower',
  TVRadioService = 'TVRadioService',
  TVSatellite = 'TVSatellite',
  TVSatelliteBS = 'TVSatelliteBS',
  TVSatelliteCS = 'TVSatelliteCS',
  TVSatelliteToggle = 'TVSatelliteToggle',
  TVTerrestrialAnalog = 'TVTerrestrialAnalog',
  TVTerrestrialDigital = 'TVTerrestrialDigital',
  TVTimer = 'TVTimer',
  AVRInput = 'AVRInput',
  AVRPower = 'AVRPower',
  ColorF0Red = 'ColorF0Red',
  ColorF1Green = 'ColorF1Green',
  ColorF2Yellow = 'ColorF2Yellow',
  ColorF3Blue = 'ColorF3Blue',
  ColorF4Grey = 'ColorF4Grey',
  ColorF5Brown = 'ColorF5Brown',
  ClosedCaptionToggle = 'ClosedCaptionToggle',
  Dimmer = 'Dimmer',
  DisplaySwap = 'DisplaySwap',
  DVR = 'DVR',
  Exit = 'Exit',
  FavoriteClear0 = 'FavoriteClear0',
  FavoriteClear1 = 'FavoriteClear1',
  FavoriteClear2 = 'FavoriteClear2',
  FavoriteClear3 = 'FavoriteClear3',
  FavoriteRecall0 = 'FavoriteRecall0',
  FavoriteRecall1 = 'FavoriteRecall1',
  FavoriteRecall2 = 'FavoriteRecall2',
  FavoriteRecall3 = 'FavoriteRecall3',
  FavoriteStore0 = 'FavoriteStore0',
  FavoriteStore1 = 'FavoriteStore1',
  FavoriteStore2 = 'FavoriteStore2',
  FavoriteStore3 = 'FavoriteStore3',
  Guide = 'Guide',
  GuideNextDay = 'GuideNextDay',
  GuidePreviousDay = 'GuidePreviousDay',
  Info = 'Info',
  InstantReplay = 'InstantReplay',
  Link = 'Link',
  ListProgram = 'ListProgram',
  LiveContent = 'LiveContent',
  Lock = 'Lock',
  MediaApps = 'MediaApps',
  MediaAudioTrack = 'MediaAudioTrack',
  MediaLast = 'MediaLast',
  MediaSkipBackward = 'MediaSkipBackward',
  MediaSkipForward = 'MediaSkipForward',
  MediaStepBackward = 'MediaStepBackward',
  MediaStepForward = 'MediaStepForward',
  MediaTopMenu = 'MediaTopMenu',
  NavigateIn = 'NavigateIn',
  NavigateNext = 'NavigateNext',
  NavigateOut = 'NavigateOut',
  NavigatePrevious = 'NavigatePrevious',
  NextFavoriteChannel = 'NextFavoriteChannel',
  NextUserProfile = 'NextUserProfile',
  OnDemand = 'OnDemand',
  Pairing = 'Pairing',
  PinPDown = 'PinPDown',
  PinPMove = 'PinPMove',
  PinPToggle = 'PinPToggle',
  PinPUp = 'PinPUp',
  PlaySpeedDown = 'PlaySpeedDown',
  PlaySpeedReset = 'PlaySpeedReset',
  PlaySpeedUp = 'PlaySpeedUp',
  RandomToggle = 'RandomToggle',
  RcLowBattery = 'RcLowBattery',
  RecordSpeedNext = 'RecordSpeedNext',
  RfBypass = 'RfBypass',
  ScanChannelsToggle = 'ScanChannelsToggle',
  ScreenModeNext = 'ScreenModeNext',
  Settings = 'Settings',
  SplitScreenToggle = 'SplitScreenToggle',
  STBInput = 'STBInput',
  STBPower = 'STBPower',
  Subtitle = 'Subtitle',
  Teletext = 'Teletext',
  VideoModeNext = 'VideoModeNext',
  Wink = 'Wink',
  ZoomToggle = 'ZoomToggle',
  F1 = 'F1',
  F2 = 'F2',
  F3 = 'F3',
  F4 = 'F4',
  F5 = 'F5',
  F6 = 'F6',
  F7 = 'F7',
  F8 = 'F8',
  F9 = 'F9',
  F10 = 'F10',
  F11 = 'F11',
  F12 = 'F12',
  F13 = 'F13',
  F14 = 'F14',
  F15 = 'F15',
  F16 = 'F16',
  F17 = 'F17',
  F18 = 'F18',
  F19 = 'F19',
  F20 = 'F20',
  F21 = 'F21',
  F22 = 'F22',
  F23 = 'F23',
  F24 = 'F24',
  F25 = 'F25',
  F26 = 'F26',
  F27 = 'F27',
  F28 = 'F28',
  F29 = 'F29',
  F30 = 'F30',
  F31 = 'F31',
  F32 = 'F32',
  F33 = 'F33',
  F34 = 'F34',
  F35 = 'F35',
  NonExhaustive = 'NonExhaustive'
}

export type NativeKey =
  | { type: 'Unidentified' }
  | { type: 'Android', code: number }
  | { type: 'MacOS', code: number }
  | { type: 'Windows', code: number }
  | { type: 'Xkb', code: number }
  | { type: 'Web', code: string }
  | { type: 'NonExhaustive' }

export type NativeKeyCode =
  | { type: 'Unidentified' }
  | { type: 'Android', code: number }
  | { type: 'MacOS', code: number }
  | { type: 'Windows', code: number }
  | { type: 'Xkb', code: number }
  | { type: 'NonExhaustive' }

export type PhysicalKey =
  | { type: 'Code', code: KeyCode }
  | { type: 'Unidentified', key: NativeKeyCode }

export type PixelUnit =
  | { type: 'Physical', count: number }
  | { type: 'Logical', count: number }

/** [winit::event::PointerKind] */
export type PointerKind =
  | { type: 'Mouse' }
  | { type: 'Touch', fingerId: FingerId }
  | { type: 'TabletTool', kind: TabletToolKind }
  | { type: 'Unknown' }
  | { type: 'NonExhaustive' }

/** [winit::event::PointerSource] */
export type PointerSource =
  | { type: 'Mouse' }
  | { type: 'Touch', fingerId: FingerId, force?: Force }
  | { type: 'TabletTool', kind: TabletToolKind, data: TabletToolData }
  | { type: 'Unknown' }
  | { type: 'NonExhaustive' }

export type Position =
  | { type: 'Physical', x: number, y: number }
  | { type: 'Logical', x: number, y: number }

export interface PreeditCursorPosition {
  begin: number
  end: number
}

export type PumpStatus =
  | { type: 'Continue' }
  | { type: 'Exit', code: number }

export declare const enum ResizeDirection {
  East = 'East',
  North = 'North',
  NorthEast = 'NorthEast',
  NorthWest = 'NorthWest',
  South = 'South',
  SouthEast = 'SouthEast',
  SouthWest = 'SouthWest',
  West = 'West'
}

export type Size =
  | { type: 'Physical', width: number, height: number }
  | { type: 'Logical', width: number, height: number }

/** [winit::event::StartCause]  */
export type StartCause =
  | { type: 'ResumeTimeReached', start: Instant, requestedResume: Instant }
  | { type: 'WaitCancelled', start: Instant, requestedResume?: Instant }
  | { type: 'Poll' }
  | { type: 'Init' }
  | { type: 'NonExhaustive' }

/** [winit::event::TabletToolAngle] */
export interface TabletToolAngle {
  altitude: number
  azimuth: number
}

/** [winit::event::TabletToolButton] */
export declare const enum TabletToolButton {
  Contact = 'Contact',
  Barrel = 'Barrel',
  NonExhaustive = 'NonExhaustive'
}

/** [winit::event::TabletToolData] */
export interface TabletToolData {
  force?: Force
  tangentialForce?: number
  twist?: number
  tilt?: TabletToolTilt
  angle?: TabletToolAngle
}

/** [winit::event::TabletToolKind] */
export declare const enum TabletToolKind {
  Pen = 'Pen',
  Eraser = 'Eraser',
  Brush = 'Brush',
  Pencil = 'Pencil',
  Airbrush = 'Airbrush',
  Finger = 'Finger',
  Mouse = 'Mouse',
  Lens = 'Lens',
  NonExhaustive = 'NonExhaustive'
}

/** [winit::event::TabletToolTilt] */
export interface TabletToolTilt {
  x: number
  y: number
}

export declare const enum Theme {
  Light = 'Light',
  Dark = 'Dark'
}

export declare const enum TouchPhase {
  Started = 'Started',
  Moved = 'Moved',
  Ended = 'Ended',
  Cancelled = 'Cancelled'
}

export declare const enum UserAttentionType {
  Critical = 'Critical',
  Informational = 'Informational'
}

export type WindowEvent =
  | { type: 'ActivationTokenDone', serial: AsyncRequestSerial, token: ActivationToken }
  | { type: 'SurfaceResized', size: Size }
  | { type: 'Moved', position: Position }
  | { type: 'CloseRequested' }
  | { type: 'Destroyed' }
  | { type: 'DragEntered', id: DataTransferId, position?: Position }
  | { type: 'DragPosition', id: DataTransferId, position: Position, proposedAction?: DndAction }
  | { type: 'DragDropped', id: DataTransferId, proposedAction?: DndAction }
  | { type: 'DragLeft', id: DataTransferId }
  | { type: 'Focused', focused: boolean }
  | { type: 'KeyboardInput', deviceId?: DeviceId, event: KeyEvent, isSynthetic: boolean }
  | { type: 'ModifiersChanged', modifiers: Modifiers }
  | { type: 'Ime', ime: Ime }
  | { type: 'PointerMoved', deviceId?: DeviceId, position: Position, primary: boolean, source: PointerSource }
  | { type: 'PointerEntered', deviceId?: DeviceId, position: Position, primary: boolean, kind: PointerKind }
  | { type: 'PointerLeft', deviceId?: DeviceId, position?: Position, primary: boolean, kind: PointerKind }
  | { type: 'MouseWheel', deviceId?: DeviceId, delta: MouseScrollDelta, phase: TouchPhase }
  | { type: 'PointerButton', deviceId?: DeviceId, state: ElementState, position: Position, primary: boolean, button: ButtonSource, isMacosActivationClick: boolean }
  | { type: 'HoldGesture', deviceId?: DeviceId, phase: TouchPhase }
  | { type: 'PinchGesture', deviceId?: DeviceId, delta: number, phase: TouchPhase }
  | { type: 'PanGesture', deviceId?: DeviceId, delta: Position, phase: TouchPhase }
  | { type: 'DoubleTapGesture', deviceId?: DeviceId }
  | { type: 'RotationGesture', deviceId?: DeviceId, delta: number, phase: TouchPhase }
  | { type: 'TouchpadPressure', deviceId?: DeviceId, pressure: number, stage: number }
  | { type: 'ScaleFactorChanged', scaleFactor: number, surfaceSizeWriter: SurfaceSizeWriter }
  | { type: 'ThemeChanged', theme: Theme }
  | { type: 'Occluded', occluded: boolean }
  | { type: 'RedrawRequested' }
  | { type: 'NonExhaustive' }

export declare const enum WindowLevel {
  AlwaysOnBottom = 'AlwaysOnBottom',
  Normal = 'Normal',
  AlwaysOnTop = 'AlwaysOnTop'
}
