// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./napi-winit.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-winit-android-arm64')
        const bindingPackageVersion = require('@ylcc/napi-winit-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./napi-winit.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-winit-android-arm-eabi')
        const bindingPackageVersion = require('@ylcc/napi-winit-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (process.config?.variables?.shlib_suffix === 'dll.a' || process.config?.variables?.node_target_type === 'shared_library') {
        try {
        return require('./napi-winit.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-winit-win32-x64-gnu')
        const bindingPackageVersion = require('@ylcc/napi-winit-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./napi-winit.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-winit-win32-x64-msvc')
        const bindingPackageVersion = require('@ylcc/napi-winit-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./napi-winit.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-winit-win32-ia32-msvc')
        const bindingPackageVersion = require('@ylcc/napi-winit-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./napi-winit.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-winit-win32-arm64-msvc')
        const bindingPackageVersion = require('@ylcc/napi-winit-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./napi-winit.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('@ylcc/napi-winit-darwin-universal')
      const bindingPackageVersion = require('@ylcc/napi-winit-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./napi-winit.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-winit-darwin-x64')
        const bindingPackageVersion = require('@ylcc/napi-winit-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./napi-winit.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-winit-darwin-arm64')
        const bindingPackageVersion = require('@ylcc/napi-winit-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./napi-winit.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-winit-freebsd-x64')
        const bindingPackageVersion = require('@ylcc/napi-winit-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./napi-winit.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-winit-freebsd-arm64')
        const bindingPackageVersion = require('@ylcc/napi-winit-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./napi-winit.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@ylcc/napi-winit-linux-x64-musl')
          const bindingPackageVersion = require('@ylcc/napi-winit-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./napi-winit.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@ylcc/napi-winit-linux-x64-gnu')
          const bindingPackageVersion = require('@ylcc/napi-winit-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./napi-winit.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@ylcc/napi-winit-linux-arm64-musl')
          const bindingPackageVersion = require('@ylcc/napi-winit-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./napi-winit.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@ylcc/napi-winit-linux-arm64-gnu')
          const bindingPackageVersion = require('@ylcc/napi-winit-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./napi-winit.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@ylcc/napi-winit-linux-arm-musleabihf')
          const bindingPackageVersion = require('@ylcc/napi-winit-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./napi-winit.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@ylcc/napi-winit-linux-arm-gnueabihf')
          const bindingPackageVersion = require('@ylcc/napi-winit-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./napi-winit.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@ylcc/napi-winit-linux-loong64-musl')
          const bindingPackageVersion = require('@ylcc/napi-winit-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./napi-winit.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@ylcc/napi-winit-linux-loong64-gnu')
          const bindingPackageVersion = require('@ylcc/napi-winit-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./napi-winit.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@ylcc/napi-winit-linux-riscv64-musl')
          const bindingPackageVersion = require('@ylcc/napi-winit-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./napi-winit.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@ylcc/napi-winit-linux-riscv64-gnu')
          const bindingPackageVersion = require('@ylcc/napi-winit-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./napi-winit.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-winit-linux-ppc64-gnu')
        const bindingPackageVersion = require('@ylcc/napi-winit-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./napi-winit.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-winit-linux-s390x-gnu')
        const bindingPackageVersion = require('@ylcc/napi-winit-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./napi-winit.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-winit-openharmony-arm64')
        const bindingPackageVersion = require('@ylcc/napi-winit-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./napi-winit.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-winit-openharmony-x64')
        const bindingPackageVersion = require('@ylcc/napi-winit-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./napi-winit.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@ylcc/napi-winit-openharmony-arm')
        const bindingPackageVersion = require('@ylcc/napi-winit-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.2.101' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.101 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./napi-winit.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding) {
    try {
      wasiBinding = require('@ylcc/napi-winit-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        wasiBindingError.cause = err
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.Duration = nativeBinding.Duration
module.exports.Extra = nativeBinding.Extra
module.exports.Instant = nativeBinding.Instant
module.exports.ActivationToken = nativeBinding.ActivationToken
module.exports.ActiveEventLoop = nativeBinding.ActiveEventLoop
module.exports.Application = nativeBinding.Application
module.exports.AsyncRequestSerial = nativeBinding.AsyncRequestSerial
module.exports.Cursor = nativeBinding.Cursor
module.exports.CustomCursor = nativeBinding.CustomCursor
module.exports.CustomCursorSource = nativeBinding.CustomCursorSource
module.exports.DeviceId = nativeBinding.DeviceId
module.exports.EventLoop = nativeBinding.EventLoop
module.exports.Icon = nativeBinding.Icon
module.exports.InnerSizeWriter = nativeBinding.InnerSizeWriter
module.exports.KeyEvent = nativeBinding.KeyEvent
module.exports.Modifiers = nativeBinding.Modifiers
module.exports.ModifiersState = nativeBinding.ModifiersState
module.exports.MonitorHandle = nativeBinding.MonitorHandle
module.exports.OwnedDisplayHandle = nativeBinding.OwnedDisplayHandle
module.exports.RawKeyEvent = nativeBinding.RawKeyEvent
module.exports.UserPayload = nativeBinding.UserPayload
module.exports.VideoModeHandle = nativeBinding.VideoModeHandle
module.exports.Window = nativeBinding.Window
module.exports.WindowAttributes = nativeBinding.WindowAttributes
module.exports.WindowButtons = nativeBinding.WindowButtons
module.exports.WindowId = nativeBinding.WindowId
module.exports.CursorGrabMode = nativeBinding.CursorGrabMode
module.exports.CursorIcon = nativeBinding.CursorIcon
module.exports.DeviceEvents = nativeBinding.DeviceEvents
module.exports.ElementState = nativeBinding.ElementState
module.exports.Fullscreen = nativeBinding.Fullscreen
module.exports.ImePurpose = nativeBinding.ImePurpose
module.exports.KeyCode = nativeBinding.KeyCode
module.exports.KeyLocation = nativeBinding.KeyLocation
module.exports.ModifiersKeyState = nativeBinding.ModifiersKeyState
module.exports.NamedKey = nativeBinding.NamedKey
module.exports.ResizeDirection = nativeBinding.ResizeDirection
module.exports.Theme = nativeBinding.Theme
module.exports.TouchPhase = nativeBinding.TouchPhase
module.exports.UserAttentionType = nativeBinding.UserAttentionType
module.exports.WindowLevel = nativeBinding.WindowLevel
